In [1]:
import pandas as pd

In [3]:
fname = "../data/snippets/validated_snippets_run21_ncses_4.6.2023.csv"
validated_snippets = pd.read_csv(fname)

In [4]:
validated_snippets

,Unnamed: 0,dyad_id,m1_score,m2_score,m3_score,m4_score,mention_candidate,snippet
0,0,634174,0.166,NaN,0.997,NaN,schools and staffing survey,d scope of minority teacher recruitment polici...
1,1,634178,0.539,0.539,0.993,0.539,common core of data,r publication of this article. \nThe offense “...
2,2,634242,0.661,NaN,0.998,NaN,education longitudinal study,students of varying levels of academic prepara...
3,3,634299,0.538,1.000,0.990,1.000,trends in international mathematics and scienc...,nsitivity of Achievement Estimation to Conditi...
4,4,634301,0.575,0.575,1.000,0.575,nces common core of data,ym districts (denoted by asterisks) have round...
...,...,...,...,...,...,...,...,...
3877,3877,890878,0.520,0.609,0.992,0.609,beginning postsecondary students longitudinal ...,ents switch meta-majors what type of major do ...
3878,3878,890936,0.718,0.718,0.998,0.718,education longitudinal study,1 -0.1\n0.0 0.0 0.0\n** ** **\n0.0 0.0 0.0\n0....
3879,3879,891062,0.427,0.373,NaN,0.373,private school universe survey,n the school supplement collected from the Nat...
3880,3880,891080,0.539,0.615,1.000,0.615,national center for education statistics commo...,2012 to 2013 school year; and West Virginia w...
3881,3881,891088,0.611,NaN,0.998,NaN,early childhood longitudinal study,ure had lowered interpersonal skills self-cont...

In [8]:
validated_snippets["max_non_model1"] = validated_snippets.loc[:, [f"m{i}_score" for i in range(2,5)]].max(axis=1)

did_poorly_on_model1 = validated_snippets["m1_score"] < 0.5
# model1_was_the_worst = validated_snippets["m1_score"] < validated_snippets["max_non_model1"]

mask = did_poorly_on_model1 #& model1_was_the_worst

validated_snippets.loc[mask, :]

,Unnamed: 0,dyad_id,m1_score,m2_score,m3_score,m4_score,mention_candidate,snippet,max_non_model1
0,0,634174,0.166,NaN,0.997,NaN,schools and staffing survey,d scope of minority teacher recruitment polici...,0.997
15,15,634575,0.490,NaN,0.997,NaN,early childhood longitudinal study,ext we introduce the empirical data used to de...,0.997
16,16,634614,0.497,NaN,0.998,NaN,beginning postsecondary students,rns and first-to-second-year persistence rates...,0.998
23,23,634729,0.423,0.501,0.998,0.501,national postsecondary student aid study,being too complicated Romano and Millard (200...,0.998
26,26,634786,0.423,0.501,0.998,0.501,national postsecondary student aid study,igher education. Thus community college studen...,0.998
...,...,...,...,...,...,...,...,...,...
3850,3850,888944,0.361,NaN,0.997,NaN,trends in international mathematics and scienc...,re the nation’s future global economic power a...,0.997
3854,3854,889332,0.467,NaN,0.998,NaN,education longitudinal study,ortance of student-and parental-level variable...,0.998
3855,3855,889849,0.433,0.246,0.997,0.246,teaching and learning international survey,bear most of the responsibility for providing...,0.997
3861,3861,890011,0.365,NaN,0.998,NaN,early childhood longitudinal study,l equivalency diploma 3 = some college 4 = bac...,0.998
3879,3879,891062,0.427,0.373,NaN,0.373,private school universe survey,n the school supplement collected from the Nat...,0.373

In [7]:
validated_snippets.loc[mask, :].to_csv(
    "../data/snippets/validated_snippets_run21_ncses_4.6.2023_fine_tune_m1.csv", 
    index=False
)